apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: default
spec:
  clusterIP: 10.99.147.205
  clusterIPs:
  - 10.99.147.205
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30305
    port: 80
  selector:
    app: api-server
  type: NodePort

